In [1]:
import numpy as np

In [3]:
a = np.array(2)

In [4]:
print(a)

2


In [5]:
np.ndim(a)

0

In [6]:
one = np.array([2,3,4,5])
two = np.array([[1,2,3,4],[2,3,4,4]])
three = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(one)
print(two)
print(three)

[2 3 4 5]
[[1 2 3 4]
 [2 3 4 4]]
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


In [7]:
np.ndim(one)

1

In [8]:
np.ndim(two)

2

In [9]:
np.ndim(three)

3

# List Vs NumPy Array

In [10]:
list1 = [1,4.0,'apple']
arr = np.array([1,2,3,4,5])


In [12]:
arr= np.array([1,2,3.9,'apple'])
arr

array(['1', '2', '3.9', 'apple'], dtype='<U32')

In [14]:
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
arr = np.array([1,2,3,4,5])
arr/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [16]:
list1/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [17]:
list2=[1,2,3,4,5]
list2/5

TypeError: unsupported operand type(s) for /: 'list' and 'int'