In [1]:
import numpy as  np

In [6]:
a = np.array([[1,2,3],[4,5,6]])


In [7]:
np.append(a,[7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.append(a,[[7,8,9]],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.append(a,[[5],[8]],axis=1)

array([[1, 2, 3, 5],
       [4, 5, 6, 8]])

## Insert Method

In [10]:
a = np.array([[1,2],
             [3,4],
             [5,6]])

In [11]:
np.insert(a,3,[11,12])

array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [15]:
np.insert(a,1,[11,12,13],axis=1)

array([[ 1, 11,  2],
       [ 3, 12,  4],
       [ 5, 13,  6]])

In [16]:
a = np.array([[1,2,3,12],
             [9,5,6,11],
             [8,4,10,7]])

In [17]:
np.delete(a,9)

array([ 1,  2,  3, 12,  9,  5,  6, 11,  8, 10,  7])

In [19]:
np.delete(a,1,axis=1)

array([[ 1,  3, 12],
       [ 9,  6, 11],
       [ 8, 10,  7]])

In [21]:
np.delete(a,1,axis=0)

array([[ 1,  2,  3, 12],
       [ 8,  4, 10,  7]])

## Hstack Vs Vstack

In [22]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [23]:
print(a,b)

[1 2 3] [4 5 6]


In [24]:
print(np.ndim(a),np.ndim(b))

1 1


In [27]:
result = np.hstack((a,b))

In [28]:
print(result)

[1 2 3 4 5 6]


In [29]:
print(np.ndim(result))

1


In [30]:
result = np.vstack((a,b))

In [31]:
print(result)

[[1 2 3]
 [4 5 6]]


## numpy concatenation

In [32]:
a = np.array([[2,4],[6,8]])
b = np.array([[3,5],[7,9]])

c=np.array([[3],[9]])
d=np.array([[4],[8]])

result = np.concatenate((a,b),axis=0)
print(result)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [34]:
new = np.concatenate((c,d),axis=1)
print(new)

[[3 4]
 [9 8]]
