In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[3,4,5],[2,4,6],[6,7,8]])

In [3]:
print(a[1,:])

[3 4 5]


In [6]:
a[1:4]

array([[3, 4, 5],
       [2, 4, 6],
       [6, 7, 8]])

In [9]:
a[:,1]

array([2, 4, 4, 7])

In [10]:
a[1, 1:3]

array([4, 5])

In [11]:
a2= np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[10,11,12],[13,14,15],[16,17,18]],
             [[19,20,21],[22,23,24],[25,26,27]]])

In [12]:
a2[1,1,1:3]

array([14, 15])

In [14]:
a2[:,1,:]

array([[ 4,  5,  6],
       [13, 14, 15],
       [22, 23, 24]])

In [17]:
a2[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## view Vs Copy

In [18]:
a = np.array([1,2,3,4,5])

copy= a.copy()
copy[0]=42
print(a)
print(copy)

[1 2 3 4 5]
[42  2  3  4  5]


In [19]:
view = a.view()
view[0]=42
print(a)
print(view)

[42  2  3  4  5]
[42  2  3  4  5]
